export const STATE_NOGAME = 'STATE_NOGAME';
export const STATE_INGAME = 'STATE_INGAME';

export const ACTION_GAME_LIST_RECIEVED = 'ACTION_GAME_LIST_RECIEVED';
export const ACTION_GAME_CREATED = 'ACTION_GAME_CREATED';
export const ACTION_GAME_JOINED = 'ACTION_GAME_JOINED';
export const ACTION_GAME_UPDATED = 'ACTION_GAME_UPDATED';
export const ACTION_GAME_STARTED = 'ACTION_GAME_STARTED'
export const ACTION_GAME_STOPPED = 'ACTION_GAME_STOPPED'
export const ACTION_GAME_LEFT = 'ACTION_GAME_LEFT';
